import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { TaskStore } from "./taskStore.js";
import { GitService } from "./gitService.js";
import { ProjectHealthService } from "./projectHealth.js";
import { safeExec } from "../utils/safeExec.js";
import { getCodexPaths, toProjectRelative } from "../utils/paths.js";
import { runDockerComposeProfile, type CheckProfile, type ProfileCheck } from "./dockerComposeProfile.js";
import { ProjectPolicyService, type ProjectPolicy } from "./projectPolicy.js";

export type SmokeResultStatus = "PASS" | "FAIL";

export interface SmokeCheck {
  name: string;
  status: "pass" | "warn" | "fail";
  details?: string;
}

export interface SmokeRunOptions {
  ephemeral?: boolean;
  profile?: CheckProfile;
  allowComposeConfigOutput?: boolean;
}

export interface SmokeResult {
  result: SmokeResultStatus;
  projectPath: string;
  ephemeral: boolean;
  profile: CheckProfile;
  allowComposeConfigOutput: boolean;
  taskId?: string;
  checks: SmokeCheck[];
  reportPath?: string;
}

interface NormalizedSmokeRunOptions {
  ephemeral: boolean;
  profile: CheckProfile;
  allowComposeConfigOutput: boolean;
}

export class SmokeRunner {
  constructor(
    private readonly taskStore = new TaskStore(),
    private readonly projectHealth = new ProjectHealthService(),
    private readonly gitService = new GitService(),
    private readonly policyService = new ProjectPolicyService()
  ) {}

  async run(projectPath: string, options: SmokeRunOptions = {}): Promise<SmokeResult> {
    const policy = await this.policyService.readPolicy(projectPath).then((result) => result.policy).catch(() => undefined);
    const normalized = normalizeOptions(options, policy);
    return normalized.ephemeral ? this.runEphemeral(projectPath, normalized) : this.runLegacy(projectPath, normalized);
  }

  private async runLegacy(projectPath: string, options: NormalizedSmokeRunOptions): Promise<SmokeResult> {
    const checks: SmokeCheck[] = [];
    const root = path.resolve(projectPath);
    let taskId: string | undefined;
    let reportPath: string | undefined;

    try {
      const healthReady = await this.checkProjectHealth(root, checks);
      if (!healthReady) {
        return this.result(root, options, checks, taskId, reportPath);
      }

      await this.runProfileChecks(root, options, checks);

      const task = await this.taskStore.createTask(root, {
        title: "Smoke check task",
        goal: "Verify Orchestrator task/report/diff workflow without changing business files.",
        context: "Generated by smoke runner legacy mode.",
        scope: ["Create a smoke task", "Create a smoke report", "Archive the smoke task"],
        outOfScope: ["Business source changes", "Tracked file changes"],
        filesAllowed: [".codex/**"],
        acceptanceCriteria: ["Task is created", "Report is readable", "Git status remains clean"],
        requiredChecks: ["git status --short"],
        notes: "This task is generated automatically by smoke runner."
      });
      taskId = task.id;
      checks.push(pass("create_smoke_task", task.taskPath));

      const state = await this.taskStore.readState(root);
      checks.push(state.tasks.some((item) => item.id === task.id) ? pass("tasks_json_contains_task", task.id) : fail("tasks_json_contains_task", task.id));

      const tasks = await this.taskStore.listTasks(root);
      checks.push(tasks.some((item) => item.id === task.id) ? pass("list_tasks", task.id) : fail("list_tasks", task.id));

      const paths = getCodexPaths(root);
      const taskReportPath = path.join(paths.reportsDir, `${task.id}-report.md`);
      await mkdir(paths.reportsDir, { recursive: true });
      await writeFile(taskReportPath, renderTaskSmokeReport(task.id, false), "utf8");
      const taskReport = await this.taskStore.readReport(root, task.id);
      checks.push(taskReport.markdown.includes(`# Report for Task ${task.id}`) ? pass("read_report", task.reportPath) : fail("read_report", task.reportPath));

      const diff = await this.gitService.inspectDiff(root, "names");
      checks.push(diff.status.trim().length === 0 && diff.output.trim().length === 0 ? pass("inspect_diff", "no tracked changes") : fail("inspect_diff", diff.output || diff.status));

      await this.taskStore.approveTask(root, task.id, "Smoke task approved automatically.");
      await this.taskStore.archiveTask(root, task.id, "Smoke task archived automatically.");
      checks.push(pass("archive_smoke_task", task.id));

      const smokeReportAbsolutePath = path.join(paths.reportsDir, `smoke-report-${timestamp()}.md`);
      reportPath = toProjectRelative(root, smokeReportAbsolutePath);
      await writeFile(smokeReportAbsolutePath, renderSmokeReport(root, task.id, checks, options), "utf8");
      checks.push(pass("create_smoke_report", reportPath));

      await this.checkGitStatus(root, checks);
    } catch (error: unknown) {
      checks.push(fail("smoke_runner", error instanceof Error ? error.message : String(error)));
    }

    return this.result(root, options, checks, taskId, reportPath);
  }

  private async runEphemeral(projectPath: string, options: NormalizedSmokeRunOptions): Promise<SmokeResult> {
    const checks: SmokeCheck[] = [];
    const root = path.resolve(projectPath);
    const paths = getCodexPaths(root);
    const smokeRoot = path.join(paths.codexDir, "smoke");
    const smokeTasksDir = path.join(smokeRoot, "tasks");
    const smokeReportsDir = path.join(smokeRoot, "reports");
    const smokeStateDir = path.join(smokeRoot, "state");
    const smokeStatePath = path.join(smokeStateDir, "tasks.json");
    const taskId = `smoke-${timestamp()}`;
    let reportPath: string | undefined;

    try {
      const healthReady = await this.checkProjectHealth(root, checks);
      if (!healthReady) {
        return this.result(root, options, checks, taskId, reportPath);
      }

      const ordinaryStateBefore = await readOptional(paths.tasksStatePath);
      const ordinaryTasksBefore = await listFileNames(paths.tasksDir);

      await this.runProfileChecks(root, options, checks);
      await mkdir(smokeTasksDir, { recursive: true });
      await mkdir(smokeReportsDir, { recursive: true });
      await mkdir(smokeStateDir, { recursive: true });

      const smokeTaskPath = path.join(smokeTasksDir, `${taskId}-task.md`);
      await writeFile(smokeTaskPath, renderEphemeralSmokeTask(taskId), "utf8");
      checks.push(pass("create_ephemeral_smoke_task", toProjectRelative(root, smokeTaskPath)));

      const smokeState = await readSmokeState(smokeStatePath);
      smokeState.tasks.push({
        id: taskId,
        status: "approved",
        taskPath: toProjectRelative(root, smokeTaskPath),
        createdAt: new Date().toISOString()
      });
      await writeFile(smokeStatePath, `${JSON.stringify(smokeState, null, 2)}\n`, "utf8");
      checks.push(pass("write_ephemeral_smoke_state", toProjectRelative(root, smokeStatePath)));

      const smokeReportAbsolutePath = path.join(smokeReportsDir, `smoke-report-${timestamp()}.md`);
      reportPath = toProjectRelative(root, smokeReportAbsolutePath);
      await writeFile(smokeReportAbsolutePath, renderSmokeReport(root, taskId, checks, options), "utf8");
      checks.push(pass("create_smoke_report", reportPath));

      const ordinaryStateAfter = await readOptional(paths.tasksStatePath);
      checks.push(ordinaryStateBefore === ordinaryStateAfter ? pass("ordinary_tasks_json_unchanged", ".codex/state/tasks.json") : fail("ordinary_tasks_json_unchanged", ".codex/state/tasks.json changed"));

      const ordinaryTasksAfter = await listFileNames(paths.tasksDir);
      checks.push(arraysEqual(ordinaryTasksBefore, ordinaryTasksAfter) ? pass("ordinary_tasks_dir_unchanged", ".codex/tasks") : fail("ordinary_tasks_dir_unchanged", ".codex/tasks changed"));

      await this.checkGitStatus(root, checks);
    } catch (error: unknown) {
      checks.push(fail("smoke_runner", error instanceof Error ? error.message : String(error)));
    }

    return this.result(root, options, checks, taskId, reportPath);
  }

  private async checkProjectHealth(root: string, checks: SmokeCheck[]): Promise<boolean> {
    const health = await this.projectHealth.check(root);
    const blockingHealthIssues = [
      !health.exists ? "project path does not exist" : undefined,
      !health.isGitRepo ? "project is not a Git repository" : undefined,
      !health.gitStatusClean ? "git status is not clean" : undefined,
      !health.codexDirExists ? ".codex is missing" : undefined,
      !health.tasksStateExists ? ".codex/state/tasks.json is missing" : undefined,
      !health.gitignoreHasCodex ? ".gitignore does not contain .codex/" : undefined
    ].filter((issue): issue is string => issue !== undefined);
    checks.push(
      blockingHealthIssues.length === 0
        ? pass("project_health", health.warnings.length ? `ready with warnings: ${health.warnings.join("; ")}` : "ready")
        : fail("project_health", blockingHealthIssues.join("; "))
    );

    return blockingHealthIssues.length === 0;
  }

  private async runProfileChecks(root: string, options: NormalizedSmokeRunOptions, checks: SmokeCheck[]): Promise<void> {
    if (options.profile !== "docker-compose") {
      return;
    }

    const profileChecks = await runDockerComposeProfile(root, {
      allowComposeConfigOutput: options.allowComposeConfigOutput
    });
    checks.push(...profileChecks.map(toSmokeCheck));
  }

  private async checkGitStatus(root: string, checks: SmokeCheck[]): Promise<void> {
    const gitStatus = await safeExec(root, "git status --short", { maxOutputBytes: 20_000 });
    checks.push(gitStatus.exitCode === 0 && gitStatus.stdout.trim().length === 0 ? pass("git_status_clean", "clean") : fail("git_status_clean", gitStatus.stdout || gitStatus.stderr));
  }

  private result(projectPath: string, options: NormalizedSmokeRunOptions, checks: SmokeCheck[], taskId?: string, reportPath?: string): SmokeResult {
    return {
      result: checks.some((check) => check.status === "fail") ? "FAIL" : "PASS",
      projectPath,
      ephemeral: options.ephemeral,
      profile: options.profile,
      allowComposeConfigOutput: options.allowComposeConfigOutput,
      taskId,
      checks,
      reportPath
    };
  }
}

export function formatSmokeText(result: SmokeResult): string {
  return [
    "MCP Orchestrator Smoke",
    "",
    `Project: ${result.projectPath}`,
    `Mode: ${result.ephemeral ? "ephemeral" : "legacy"}`,
    `Profile: ${result.profile}`,
    ...result.checks.map((check) => `[${check.status.toUpperCase()}] ${check.name}${check.details ? ` - ${check.details}` : ""}`),
    result.reportPath ? `Report: ${result.reportPath}` : undefined,
    "",
    `Result: ${result.result}`
  ]
    .filter((line): line is string => line !== undefined)
    .join("\n");
}

function renderTaskSmokeReport(taskId: string, ephemeral: boolean): string {
  return [
    `# Report for Task ${taskId}`,
    "",
    "## Summary",
    "",
    ephemeral ? "Ephemeral smoke task report generated by smoke runner." : "Smoke task report generated by smoke runner legacy mode.",
    "",
    "## Changed Files",
    "",
    ephemeral ? "- .codex/smoke only" : "- .codex only",
    "",
    "## Checks Run",
    "",
    "- git status --short - pass",
    "",
    "## Manual Verification",
    "",
    "Verified task/report/read/diff workflow.",
    "",
    "## Problems",
    "",
    "No problems found.",
    "",
    "## Security Notes",
    "",
    "No business files or secrets were changed.",
    "",
    "## Next Step Proposal",
    "",
    "Continue normal Orchestrator workflow.",
    ""
  ].join("\n");
}

function renderEphemeralSmokeTask(taskId: string): string {
  return [
    `# Smoke Task ${taskId}`,
    "",
    "## Goal",
    "",
    "Verify Orchestrator readiness without consuming normal task IDs.",
    "",
    "## Scope",
    "",
    "- Write only inside `.codex/smoke`.",
    "- Keep `.codex/state/tasks.json` unchanged.",
    "- Keep `.codex/tasks` unchanged.",
    ""
  ].join("\n");
}

function renderSmokeReport(projectPath: string, taskId: string, checks: SmokeCheck[], options: NormalizedSmokeRunOptions): string {
  return [
    "# Smoke Report",
    "",
    `Project: ${projectPath}`,
    `Task: ${taskId}`,
    `Mode: ${options.ephemeral ? "ephemeral" : "legacy"}`,
    `Profile: ${options.profile}`,
    `Allow compose config output: ${options.allowComposeConfigOutput}`,
    "",
    "## Checks",
    "",
    ...checks.map((check) => `- ${check.name} - ${check.status}${check.details ? ` - ${check.details}` : ""}`),
    "",
    "## Security Notes",
    "",
    "- Full `docker compose config` output is not stored by default because it may contain resolved env values.",
    ""
  ].join("\n");
}

async function readOptional(filePath: string): Promise<string | undefined> {
  return readFile(filePath, "utf8").catch(() => undefined);
}

async function listFileNames(dirPath: string): Promise<string[]> {
  const entries = await readdir(dirPath).catch(() => []);
  return entries.sort();
}

interface EphemeralSmokeState {
  tasks: Array<{
    id: string;
    status: "approved";
    taskPath: string;
    createdAt: string;
  }>;
}

async function readSmokeState(filePath: string): Promise<EphemeralSmokeState> {
  const content = await readOptional(filePath);
  if (!content) {
    return { tasks: [] };
  }

  try {
    const parsed = JSON.parse(content) as EphemeralSmokeState;
    return Array.isArray(parsed.tasks) ? parsed : { tasks: [] };
  } catch {
    return { tasks: [] };
  }
}

function arraysEqual(left: string[], right: string[]): boolean {
  return left.length === right.length && left.every((item, index) => item === right[index]);
}

function toSmokeCheck(check: ProfileCheck): SmokeCheck {
  return { name: check.name, status: check.status, details: check.details };
}

function pass(name: string, details?: string): SmokeCheck {
  return { name, status: "pass", details };
}

function fail(name: string, details?: string): SmokeCheck {
  return { name, status: "fail", details };
}

function timestamp(): string {
  const now = new Date();
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

function normalizeOptions(options: SmokeRunOptions, policy?: ProjectPolicy): NormalizedSmokeRunOptions {
  return {
    ephemeral: options.ephemeral ?? policy?.defaultSmokeMode === "ephemeral",
    profile: options.profile ?? policy?.defaultProfile ?? "default",
    allowComposeConfigOutput: options.allowComposeConfigOutput ?? false
  };
}
