import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { TaskStore } from "./taskStore.js";
import { GitService } from "./gitService.js";
import { ProjectHealthService } from "./projectHealth.js";
import { safeExec } from "../utils/safeExec.js";
import { getCodexPaths, toProjectRelative } from "../utils/paths.js";

export type SmokeResultStatus = "PASS" | "FAIL";

export interface SmokeCheck {
  name: string;
  status: "pass" | "fail";
  details?: string;
}

export interface SmokeResult {
  result: SmokeResultStatus;
  projectPath: string;
  taskId?: string;
  checks: SmokeCheck[];
  reportPath?: string;
}

export class SmokeRunner {
  constructor(
    private readonly taskStore = new TaskStore(),
    private readonly projectHealth = new ProjectHealthService(),
    private readonly gitService = new GitService()
  ) {}

  async run(projectPath: string): Promise<SmokeResult> {
    const checks: SmokeCheck[] = [];
    const root = path.resolve(projectPath);
    let taskId: string | undefined;
    let reportPath: string | undefined;

    try {
      const health = await this.projectHealth.check(root);
      const blockingHealthIssues = [
        !health.exists ? "project path does not exist" : undefined,
        !health.isGitRepo ? "project is not a Git repository" : undefined,
        !health.gitStatusClean ? "git status is not clean" : undefined,
        !health.codexDirExists ? ".codex is missing" : undefined,
        !health.tasksStateExists ? ".codex/state/tasks.json is missing" : undefined,
        !health.gitignoreHasCodex ? ".gitignore does not contain .codex/" : undefined
      ].filter((issue): issue is string => issue !== undefined);
      checks.push(
        blockingHealthIssues.length === 0
          ? pass("project_health", health.warnings.length ? `ready with warnings: ${health.warnings.join("; ")}` : "ready")
          : fail("project_health", blockingHealthIssues.join("; "))
      );
      if (blockingHealthIssues.length > 0) {
        return this.result(root, checks, taskId, reportPath);
      }

      const task = await this.taskStore.createTask(root, {
        title: "Smoke check task",
        goal: "Verify Orchestrator task/report/diff workflow without changing business files.",
        context: "Generated by MVP-4 smoke runner.",
        scope: ["Create a smoke task", "Create a smoke report", "Archive the smoke task"],
        outOfScope: ["Business source changes", "Tracked file changes"],
        filesAllowed: [".codex/**"],
        acceptanceCriteria: ["Task is created", "Report is readable", "Git status remains clean"],
        requiredChecks: ["git status --short"],
        notes: "This task is generated automatically by smoke runner."
      });
      taskId = task.id;
      checks.push(pass("create_smoke_task", task.taskPath));

      const state = await this.taskStore.readState(root);
      checks.push(state.tasks.some((item) => item.id === task.id) ? pass("tasks_json_contains_task", task.id) : fail("tasks_json_contains_task", task.id));

      const tasks = await this.taskStore.listTasks(root);
      checks.push(tasks.some((item) => item.id === task.id) ? pass("list_tasks", task.id) : fail("list_tasks", task.id));

      const paths = getCodexPaths(root);
      const taskReportPath = path.join(paths.reportsDir, `${task.id}-report.md`);
      await mkdir(paths.reportsDir, { recursive: true });
      await writeFile(taskReportPath, renderTaskSmokeReport(task.id), "utf8");
      const taskReport = await this.taskStore.readReport(root, task.id);
      checks.push(taskReport.markdown.includes(`# Report for Task ${task.id}`) ? pass("read_report", task.reportPath) : fail("read_report", task.reportPath));

      const diff = await this.gitService.inspectDiff(root, "names");
      checks.push(diff.status.trim().length === 0 && diff.output.trim().length === 0 ? pass("inspect_diff", "no tracked changes") : fail("inspect_diff", diff.output || diff.status));

      await this.taskStore.approveTask(root, task.id, "Smoke task approved automatically.");
      await this.taskStore.archiveTask(root, task.id, "Smoke task archived automatically.");
      checks.push(pass("archive_smoke_task", task.id));

      const smokeReportAbsolutePath = path.join(paths.reportsDir, `smoke-report-${timestamp()}.md`);
      reportPath = toProjectRelative(root, smokeReportAbsolutePath);
      await writeFile(smokeReportAbsolutePath, renderSmokeReport(root, task.id, checks), "utf8");
      checks.push(pass("create_smoke_report", reportPath));

      const gitStatus = await safeExec(root, "git status --short", { maxOutputBytes: 20_000 });
      checks.push(gitStatus.exitCode === 0 && gitStatus.stdout.trim().length === 0 ? pass("git_status_clean", "clean") : fail("git_status_clean", gitStatus.stdout || gitStatus.stderr));
    } catch (error: unknown) {
      checks.push(fail("smoke_runner", error instanceof Error ? error.message : String(error)));
    }

    return this.result(root, checks, taskId, reportPath);
  }

  private result(projectPath: string, checks: SmokeCheck[], taskId?: string, reportPath?: string): SmokeResult {
    return {
      result: checks.some((check) => check.status === "fail") ? "FAIL" : "PASS",
      projectPath,
      taskId,
      checks,
      reportPath
    };
  }
}

export function formatSmokeText(result: SmokeResult): string {
  return [
    "MCP Orchestrator Smoke",
    "",
    `Project: ${result.projectPath}`,
    ...result.checks.map((check) => `[${check.status === "pass" ? "PASS" : "FAIL"}] ${check.name}${check.details ? ` - ${check.details}` : ""}`),
    result.reportPath ? `Report: ${result.reportPath}` : undefined,
    "",
    `Result: ${result.result}`
  ]
    .filter((line): line is string => line !== undefined)
    .join("\n");
}

function renderTaskSmokeReport(taskId: string): string {
  return [
    `# Report for Task ${taskId}`,
    "",
    "## Summary",
    "",
    "Smoke task report generated by MVP-4 smoke runner.",
    "",
    "## Changed Files",
    "",
    "- .codex only",
    "",
    "## Checks Run",
    "",
    "- git status --short - pass",
    "",
    "## Manual Verification",
    "",
    "Verified task/report/read/diff workflow.",
    "",
    "## Problems",
    "",
    "No problems found.",
    "",
    "## Security Notes",
    "",
    "No business files or secrets were changed.",
    "",
    "## Next Step Proposal",
    "",
    "Continue normal Orchestrator workflow.",
    ""
  ].join("\n");
}

function renderSmokeReport(projectPath: string, taskId: string, checks: SmokeCheck[]): string {
  return [
    "# Smoke Report",
    "",
    `Project: ${projectPath}`,
    `Task: ${taskId}`,
    "",
    "## Checks",
    "",
    ...checks.map((check) => `- ${check.name} - ${check.status}${check.details ? ` - ${check.details}` : ""}`),
    ""
  ].join("\n");
}

function pass(name: string, details?: string): SmokeCheck {
  return { name, status: "pass", details };
}

function fail(name: string, details?: string): SmokeCheck {
  return { name, status: "fail", details };
}

function timestamp(): string {
  const now = new Date();
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}
