export const toolNames = [
  "create_task",
  "get_task_status",
  "read_report",
  "inspect_diff",
  "run_tests",
  "approve_task",
  "reject_task",
  "create_next_task",
  "relay_status",
  "codex_next",
  "project_health",
  "list_tasks",
  "archive_task",
  "doctor",
  "smoke_check",
  "read_policy",
  "validate_task_against_policy",
  "validate_diff_against_policy",
  "review_gate",
  "project_status"
] as const;
